paso1:
  url: "https://century21mexico.com/"
  headers:
    Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
    Accept-Encoding: "gzip, deflate, br, zstd"
    Accept-Language: "es-MX,es;q=0.8,en-US;q=0.5,en;q=0.3"
    Connection: "keep-alive"
    DNT: "1"
    Host: "century21mexico.com"
    Priority: "u=0, i"
    Sec-Fetch-Dest: "document"
    Sec-Fetch-Mode: "navigate"
    Sec-Fetch-Site: "none"
    Sec-Fetch-User: "?1"
    Sec-GPC: "1"
    Upgrade-Insecure-Requests: "1"
    User-Agent: "__USER_AGENT__"

paso2:
  url: "https://century21mexico.com/v/resultados?json=true"
  headers:
    Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
    Accept-Encoding: "gzip, deflate, br, zstd"
    Accept-Language: "es-MX,es;q=0.8,en-US;q=0.5,en;q=0.3"
    Connection: "keep-alive"
    DNT: "1"
    Host: "century21mexico.com"
    Priority: "u=0, i"
    Sec-Fetch-Dest: "document"
    Sec-Fetch-Mode: "navigate"
    Sec-Fetch-Site: "none"
    Sec-Fetch-User: "?1"
    Sec-GPC: "1"
    Upgrade-Insecure-Requests: "1"
    User-Agent: "__USER_AGENT__"
